import Head from 'next/head';
import Banner from '../components/Banner';
import Header from '../components/Header';
import { sanityClient } from '../sanity.js';
import { Posts } from '../typing';
import EachPosts from '../components/EachPosts';

interface Props {
  posts: Posts[];
}

export default function Home({ posts }: Props) {
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />

      <EachPosts posts={posts} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = `*[_type == "post"]{
    _id,
    title,
    author -> {
    name,
    image,
    },
    description,
    mainImage,
    slug
  }`;

  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    },
  };
};
